### ISSUE TITLE
Colors example fails to start

### ISSUE THREAD

**Issue by mpetrun5** [sygmaprotocol/sygma-sdk#133]
Colors example fails to start and returns errors (probably related to new version of sdk?).
Also, would be nice to be able to set environment variables for it in some .env file to be able to 
deploy for devnet.

**Comment by wainola** [comment]
this issue is going to be solve doing the following:

- current examples are using outdated function to create the deposit data. We need to use the latest one
- examples need to use latest version on `sygma-contract` and `sdk`
- we should remove calling `setAdminResource` from the script that's deploying the `colors` contract

Futher improvements:

- update readme with instructions and explanations.
- comment the code of the example

**Comment by wainola** [comment]
Update: the PR for this issue is currently stale. Majority of the comments had been addressed execept for two regarding not using `any` annotation. There is an issue with the usage of the internal dependency of the monorepo that throws error when trying to run the example. We need to debug this as this is affecting all the examples.

What I proposed here is to merge the current PR, since `colors` examples are using latest methods referencing current version of `permissionless` generic handler inside the SDK and create another issue or issues to address the problems with all the examples that are not working properly.

**Comment by mpetrun5** [comment]
Will be revisited after the generic message passing update to the SDK
