### ISSUE TITLE
Deposits fail because of gas estimation

### ISSUE THREAD

**Issue by nmlinaric** [sygmaprotocol/sygma-sdk#202]
transfer ui is broken after I would say [substrate support PR](https://github.com/sygmaprotocol/sygma-sdk/pull/189/files#diff-19c1b674b0f79de4acd307d31f8d2282c5fd4c636f20ca38a7f3bcf716106514) got merged.
Tested from Sepolia to Moonbase/Mumbai
 Screenshot is
![here](https://user-images.githubusercontent.com/35880252/225610381-c7f8d2ed-0019-4025-88f6-a72e0fab4f1f.png)

## Expected Behavior
Bridge works

## Current Behavior
Bridge doesn't work

**Comment by wainola** [comment]
Update: current transfer UI has sdk version 1.3.0. Although before updating to this version there were somes issues with fee data length when trying to transfer LR token, those issues are no longer present. 

Before the merge of `share-config` implemnetation on the transfer UI, I did a sanity check with the UI connected to devnet. The primary results of this were:

- there was no proposal execution from sepolia to moonbase using LR token
- there was no proposal execution from goerli to moonbase using the LR token
- there was no deposit from moonbase to mumbai using LR token

Once `shared-config` was merge, I did a re-test over those edge cases and there were no issues found trying to transfer the tokens.

- success on proposal exeuction [here](https://moonbase.moonscan.io/tx/0xd608b1e3d41422d12c78b783d0ed7f3f8d10f4b19651e9b04a1b008840390c23). Deposit on sepolia [here](https://sepolia.etherscan.io/tx/0xa67e72417cff2cec5922a1a69fb0ebf2125b3febe7cd5d53be91d3a7fd804314)
- success on proposal execution [here](https://moonbase.moonscan.io/tx/0x37a494007f86bddd8678e546cfe40a2b4b274872badbd2b96da20e34b9d12e99). Deposit on goerli[here](https://goerli.etherscan.io/tx/0xc6f6bab07499426e9ba6d6493e2541669c8c109873c3ac56a68f2cf135463096)
- success deposit on moonbase [here](https://moonbase.moonscan.io/tx/0xed13f6ce23246795a8e404e519a4c8525fb87b03be4b619c80ef251c70294003). Proposal execution on mumbai [here](https://mumbai.polygonscan.com/tx/0xe0b712fcf13690aff2d79dd034a1ee577c1a628d5dd631692cbf5bbe99b5a5ba)

Sometimes, due to 5 blocks confirmation,s UI doesn't capture the proposal execution event, hence the UI doesn't update to the final state of transfer complete. Apart from some slow deposit usually with goerli and sometimes sepolia, there is no issue currently with transfer ui as reported above
